### ISSUE TITLE
Commit Issue

### ISSUE THREAD

**Issue by xVoidie** [Spuckwaffel/dumpspace#311]
Hi, I just wanted to report a small bug/issue that i have been having, It seems to only happen when adding a new game using either Dumper-7 or UEDumper Development branch using version 10202

![image](https://github.com/user-attachments/assets/ee9ebef9-a948-44f4-b86d-d98f92897a4c)

**Comment by xVoidie** [comment]
also might add that i am using the most up to date version of both UEDumper and Dumper-7

**Comment by Spuckwaffel** [comment]
hey there, this was an issue on my end and has been fixed. thanks for the report!

**Comment by xVoidie** [comment]
No problem, thanks for letting me know, I will try again now
